spring:
  datasource:
    url: jdbc:h2:mem://db
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    com.example.testing: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
