spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testing-db
    username: dev
    password: dev123
  jpa:
    hibernate:
      ddl-auto: update
security:
  jwt:
    secret: jwt.super.secret.key
    # token expires in 7 days
    token-expiration-time-min: 10080
